# Generated by Django 2.2.9 on 2020-01-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
